# clash 文档
# https://dreamacro.github.io/clash/zh_CN/
#
# 参考配置：
# https://gist.github.com/miaomiaoclub/6947f7cb93846301f1658da0edcd61bf

# HTTP(S) and SOCKS5 共用端口
mixed-port: 7890
allow-lan: true
# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule
# 5 个级别：silent / info / warning / error / debug
log-level: info


# RESTful Web API 监听地址
external-controller: 127.0.0.1:9090

# 配置目录的相对路径或静态 Web 资源目录的绝对路径. Clash core 将在
# `http://{{external-controller}}/ui` 中提供服务.
# external-ui: folder

# RESTful API 密钥 (可选)
# 通过指定 HTTP 头 `Authorization: Bearer ${secret}` 进行身份验证
# 如果RESTful API在 0.0.0.0 上监听, 务必设置一个 secret 密钥.
secret: "111111"

# 本地 SOCKS5/HTTP(S) 代理服务的认证
# authentication:
#  - "admin:pass1"

# DNS服务器设置
# 如果不设置，DNS服务器将被禁用。
# 参考 https://sakanoy.com/2021/06/23/ClashX%E4%BD%BF%E7%94%A8%E5%85%A5%E9%97%A8/
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 CIDR
  # 不使用fakeip解析，返回真实ip
  fake-ip-filter:
    # === LAN ===
    - '*.lan'
    ## QQ Quick Login
    - localhost.ptlogin2.qq.com
  default-nameserver:
    - 114.114.114.114 #114dns
    - 119.29.29.29 #腾讯云
    - 223.5.5.5 # 阿里云 
    - 185.222.222.222 #DNS.SB
    - 9.9.9.9 #IBM-Quad9
    - 1.1.1.1 #Cloudflare
    - 1.0.0.1 #Cloudflare
    - 8.8.8.8 #Google
    - 101.101.101.101 #TWNIC-Quad101
  # 支持 UDP, TCP, DoT, DoH. 和指定端口
  nameserver:
    - tls://dns.pub #腾讯云
    - https://doh.pub/dns-query #腾讯云
    - https://dns.alidns.com/dns-query #阿里云
    - https://rubyfish.cn/dns-query #红鱼
    - https://doh.360.cn/dns-query #360
    - https://doh.sb/dns-query #DNS.SB
    - https://doh-jp.blahdns.com/dns-query #blahdns
    - https://doh-de.blahdns.com/dns-query #blahdns
  fallback:
    - tls://1.1.1.1:853 # cloudflare DNS over TLS
    - tls://8.8.8.8:853 # Google DNS over TLS
    - tls://8.8.4.4:853 
    - https://1.1.1.1/dns-query # cloudflare DNS over HTTPS
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query # Google DNS over HTTPS
    - https://dns.twnic.tw/dns-query #Quad 101
    - https://dns.adguard.com/dns-query #AdGuard
    - https://dns.quad9.net/dns-query #IBM-Quad9
    - https://doh.opendns.com/dns-query #OpenDNS
  fallback-filter:
    geoip: true
    geoip-code: CN
    # 这些子网ip视为污染ip，如果nameserver的结果为这些，则使用fallback的结果
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    # 被污染的域名，如果查找的域名为这些，则使用fallback的结果
    domain:
      - '+.google.com'
      - '+.youtube.com'

# tun:
#   enable: true
#   # system / gvisor
#   # 好像仅 Linux、macOS 或 Android 下可以使用system 
#   stack: gvisor
#   auto-route: true # 自动设置 Windows 的全局路由， 管理 `ip route` 和 `ip rules`
#   auto-redir: true # 管理 nftable REDIRECT
#   auto-detect-interface: true # 自动检测接口 与 `interface-name`配置 冲突
#   dns-hijack:
#     - 198.18.0.2:53 # 当 `fake-ip-range` 是 198.18.0.1/16 时，应劫持 198.18.0.2:53
#     # - 8.8.8.8:53
#     # - tcp://8.8.8.8:53
#     # - any:53
#     # - tcp://any:53


# url订阅链接, 订阅文件应当为 yaml 格式, 否则应当进行订阅转换
proxy-providers:
  proxy-pro:
    type: http
    url: https%3A%2F%2Fchiguayun.com%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D55af3d4498fdc707d4cf331e498e5554&target=clash
    path: ./proxy/proxy.yml
    interval: 86400
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - DIRECT

  # 策略组
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择

  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连

# clash-rules项目提供的规则集
# https://github.com/Loyalsoldier/clash-rules
#
# 遇到无法访问的情况可以使用 github 代理地址
# https://ghproxy.com/*
rule-providers:
  steam:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Steam.yaml"
    path: ./ruleset/Steam.yaml
    interval: 86400

  # ACL4SSR 常见广告关键字
  banad:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
    path: ./ruleset/BanAD.yaml
    interval: 86400

  # iCloud 域名列表
  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  # Apple 在中国大陆可直连的域名列表
  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  # [慎用]Google 在中国大陆可直连的域名列表 
  google:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  # 代理域名列表
  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  # 直连域名列表
  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  # 私有网络专用域名列表
  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  # GFWList 域名列表
  gfw:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  # 非中国大陆使用的顶级域名列表 tld-not-cn
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  # Telegram 使用的 IP 地址列表
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  # 中国大陆 IP 地址列表
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  # 局域网 IP 及保留 IP 地址列表
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  # 需要直连的常见软件列表
  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  # DOMAIN-SUFFIX：域名后缀匹配
  # DOMAIN-KEYWORD：域名关键字匹配
  #
  # IP-CIDR：IP 段匹配
  # GEOIP : 通过解析的 ip 所属地进行分流。
  # MATCH : 全匹配 , 一般放在最后
  
  - DOMAIN-SUFFIX,tttttttt.xx,🎯 全球直连

  # 需要直连的规则集
  - RULE-SET,lancidr,🎯 全球直连
  - RULE-SET,applications,🎯 全球直连
  - RULE-SET,private,🎯 全球直连
  - RULE-SET,icloud,🎯 全球直连
  - RULE-SET,apple,🎯 全球直连
  - RULE-SET,google,🎯 全球直连
  - RULE-SET,direct,🎯 全球直连
  - RULE-SET,cncidr,🎯 全球直连

  # 广告拦截
  - RULE-SET,banad,🛑 全球拦截

  # 代理 集
  - RULE-SET,proxy,🚀 节点选择
  - RULE-SET,tld-not-cn,🚀 节点选择
  - RULE-SET,gfw,🚀 节点选择
  - RULE-SET,telegramcidr,🚀 节点选择
  - RULE-SET,steam,🚀 节点选择

  # LAN
  - GEOIP,LAN,DIRECT
  
  # 最后匹配
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼
  
